<?xml version="1.0" encoding="UTF-8"?>
<!--
  Copyright 2024-present fuhouyu.
 
  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at
 
       https://www.apache.org/licenses/LICENSE-2.0
 
  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
-->
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.fuhouyu</groupId>
        <artifactId>base-framework</artifactId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>base-framework-bom</artifactId>
    <name>Base Framework Bom</name>
    <description>基础框架依赖定义</description>
    <packaging>pom</packaging>


    <properties>
        <lombok-maven-plugin.version>1.18.20.0</lombok-maven-plugin.version>
        <versions-maven-plugin.version>2.21.0</versions-maven-plugin.version>
        <easyj-maven-plugin.version>1.1.5</easyj-maven-plugin.version>
        <native-maven-plugin.version>0.11.4</native-maven-plugin.version>
        <exec-maven-plugin.version>3.6.3</exec-maven-plugin.version>
        <maven-gpg-plugin.version>3.2.8</maven-gpg-plugin.version>
        <central-publishing-maven-plugin.version>0.10.0</central-publishing-maven-plugin.version>

        <spring-boot-dependencies.version>4.1.0-M1</spring-boot-dependencies.version>
        <spring-cloud-dependencies.version>2025.1.1</spring-cloud-dependencies.version>
        <spring-cloud-alibaba-dependencies.version>2025.1.0.0</spring-cloud-alibaba-dependencies.version>
        <springdoc-openapi-starter-webmvc-api.version>3.0.1</springdoc-openapi-starter-webmvc-api.version>
        <spring-boot-starter-data-redis.version>4.1.0-M1</spring-boot-starter-data-redis.version>
        <kryo5.version>5.6.0</kryo5.version>
        <jackson-bom.version>2.18.3</jackson-bom.version>
        <aliyun-sdk-oss.version>3.18.5</aliyun-sdk-oss.version>
        <bcprov-jdk18on.version>1.83</bcprov-jdk18on.version>
        <hutool-bom.version>5.8.43</hutool-bom.version>
        <commons-lang3.version>3.20.0</commons-lang3.version>
        <lombok.version>1.18.42</lombok.version>
        <mapstruct-processor.version>1.7.0.Beta1</mapstruct-processor.version>
        <jasypt-spring-boot-starter.version>4.0.4</jasypt-spring-boot-starter.version>
        <lombok-mapstruct-binding.version>0.2.0</lombok-mapstruct-binding.version>
        <bom.version>2.41.26</bom.version>
        <docs-integration-sdk.version>1.7.1</docs-integration-sdk.version>
        <ip2region.version>3.3.4</ip2region.version>
        <sts20150401.version>1.2.0</sts20150401.version>
        <transmittable-thread-local.version>2.14.5</transmittable-thread-local.version>
        <oshi-core.version>6.9.3</oshi-core.version>
        <fastexcel.version>1.3.0</fastexcel.version>

        <druid-spring-boot-starter.version>1.2.27</druid-spring-boot-starter.version>
        <mysql-connector-j.version>9.6.0</mysql-connector-j.version>
        <postgresql.version>42.7.9</postgresql.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>software.amazon.awssdk</groupId>
                <artifactId>bom</artifactId>
                <version>${bom.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring-boot-dependencies.version}</version>
                <scope>import</scope>
                <type>pom</type>
            </dependency>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud-dependencies.version}</version>
                <scope>import</scope>
                <type>pom</type>
            </dependency>
            <dependency>
                <groupId>com.alibaba.cloud</groupId>
                <artifactId>spring-cloud-alibaba-dependencies</artifactId>
                <version>${spring-cloud-alibaba-dependencies.version}</version>
                <scope>import</scope>
                <type>pom</type>
            </dependency>
            <dependency>
                <groupId>cn.hutool</groupId>
                <artifactId>hutool-bom</artifactId>
                <version>${hutool-bom.version}</version>
                <scope>import</scope>
                <type>pom</type>
            </dependency>

            <dependency>
                <groupId>org.springdoc</groupId>
                <artifactId>springdoc-openapi-starter-common</artifactId>
                <version>${springdoc-openapi-starter-webmvc-api.version}</version>
            </dependency>
            <dependency>
                <groupId>org.springdoc</groupId>
                <artifactId>springdoc-openapi-starter-webmvc-api</artifactId>
                <version>${springdoc-openapi-starter-webmvc-api.version}</version>
            </dependency>
            <dependency>
                <groupId>org.babyfish.jimmer</groupId>
                <artifactId>jimmer-spring-boot-starter</artifactId>
                <version>${jimmer.version}</version>
            </dependency>
            <dependency>
                <groupId>org.babyfish.jimmer</groupId>
                <artifactId>jimmer-sql</artifactId>
                <version>${jimmer.version}</version>
            </dependency>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-data-redis</artifactId>
                <version>${spring-boot-starter-data-redis.version}</version>
            </dependency>
            <dependency>
                <groupId>com.alibaba</groupId>
                <artifactId>druid-spring-boot-starter</artifactId>
                <version>${druid-spring-boot-starter.version}</version>
            </dependency>
            <dependency>
                <groupId>com.mysql</groupId>
                <artifactId>mysql-connector-j</artifactId>
                <version>${mysql-connector-j.version}</version>
            </dependency>
            <dependency>
                <groupId>org.postgresql</groupId>
                <artifactId>postgresql</artifactId>
                <version>${postgresql.version}</version>
            </dependency>
            <dependency>
                <groupId>com.esotericsoftware</groupId>
                <artifactId>kryo5</artifactId>
                <version>${kryo5.version}</version>
            </dependency>
            <dependency>
                <groupId>com.aliyun.oss</groupId>
                <artifactId>aliyun-sdk-oss</artifactId>
                <version>${aliyun-sdk-oss.version}</version>
            </dependency>
            <dependency>
                <groupId>org.bouncycastle</groupId>
                <artifactId>bcprov-jdk18on</artifactId>
                <version>${bcprov-jdk18on.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-lang3</artifactId>
                <version>${commons-lang3.version}</version>
            </dependency>
            <dependency>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok</artifactId>
                <version>${lombok.version}</version>
            </dependency>
            <dependency>
                <groupId>org.mapstruct</groupId>
                <artifactId>mapstruct</artifactId>
                <version>${mapstruct-processor.version}</version>
            </dependency>
            <dependency>
                <groupId>com.github.ulisesbocchio</groupId>
                <artifactId>jasypt-spring-boot-starter</artifactId>
                <version>${jasypt-spring-boot-starter.version}</version>
            </dependency>
            <dependency>
                <groupId>com.onlyoffice</groupId>
                <artifactId>docs-integration-sdk</artifactId>
                <version>${docs-integration-sdk.version}</version>
            </dependency>
            <dependency>
                <groupId>org.lionsoul</groupId>
                <artifactId>ip2region</artifactId>
                <version>${ip2region.version}</version>
            </dependency>
            <dependency>
                <groupId>com.aliyun</groupId>
                <artifactId>sts20150401</artifactId>
                <version>${sts20150401.version}</version>
            </dependency>
            <dependency>
                <groupId>com.alibaba</groupId>
                <artifactId>transmittable-thread-local</artifactId>
                <version>${transmittable-thread-local.version}</version>
            </dependency>
            <dependency>
                <groupId>com.github.oshi</groupId>
                <artifactId>oshi-core</artifactId>
                <version>${oshi-core.version}</version>
            </dependency>
            <dependency>
                <groupId>cn.idev.excel</groupId>
                <artifactId>fastexcel</artifactId>
                <version>${fastexcel.version}</version>
            </dependency>
            <dependency>
                <groupId>com.fuhouyu</groupId>
                <artifactId>base-framework-context</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.fuhouyu</groupId>
                <artifactId>base-framework-cache-starter</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.fuhouyu</groupId>
                <artifactId>base-framework-log-starter</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.fuhouyu</groupId>
                <artifactId>base-framework-common</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.fuhouyu</groupId>
                <artifactId>base-framework-oauth-starter</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.fuhouyu</groupId>
                <artifactId>base-framework-web-starter</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.fuhouyu</groupId>
                <artifactId>base-framework-resource-starter</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.fuhouyu</groupId>
                <artifactId>base-framework-kms-starter</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.fuhouyu</groupId>
                <artifactId>base-framework-s3-starter</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.fuhouyu</groupId>
                <artifactId>base-framework-database-starter</artifactId>
                <version>${project.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>