spring:
  application:
    name: test
base:
  framework:
    web:
      user-class-name: com.fuhouyu.framework.context.user.DefaultUserDetail
    cache:
      service:
        cache-service-type: caffeine
    kms:
      default:
        sm2:
          auto-generate: true