name: ci
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - feature/1.0.0
  pull_request_target:
    branches: [ develop ]

permissions: read-all

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: "Cache Maven Repos"
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Set up JDK 21"
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          server-id: ossrh
          server-username: ${{ secrets.OSSRH_USERNAME }}
          server-password: ${{ secrets.OSSRH_TOKEN }}
      # 发布到中央仓库
      - name: Tests
        run: mvn --batch-mode clean test
      - name: "Upload test results to Codecov"
        if: ${{ !cancelled() }}
        uses: codecov/codecov-action@v4.2.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./*/target/site/jacoco/jacoco.xml