name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - develop

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Qodana Scan
        uses: JetBrains/qodana-action@v2024.1
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
      - name: Build with Maven
        run: mvn clean test
      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        files: target/surefire-reports/*.xml
        with:
          token: ${{ secrets.CODECOV_TOKEN }}