name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - develop

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - name: "Cache Maven Repos"
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Qodana Scan
        uses: JetBrains/qodana-action@v2024.1
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
      - name: Build with Maven
        run: mvn clean test
      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/codecov-action@v4.2.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
          fail_ci_if_error: true
          files:
            - ./base-framework-cache-starter/target/site/jacoco/jacoco.xml
            - ./base-framework-context/target/site/jacoco/jacoco.xml
            - ./base-framework-kms-starter/target/site/jacoco/jacoco.xml
            - ./base-framework-log-starter/target/site/jacoco/jacoco.xml
            - ./base-framework-resource-starter/target/site/jacoco/jacoco.xml
            - ./base-framework-security-starter/target/site/jacoco/jacoco.xml
            - ./base-framework-web-starter/target/site/jacoco/jacoco.xml
